const CHAT_EVENTS = {
    CHAT_CHANNEL: 'CHAT',
    NEW_CHAT_EVENT: 'NEW-CHAT',
    CHAT_EVENT_ACCEPT: 'CHAT-ACCEPTED',
    CHAT_EVENT_CLOSED: 'CHAT-ACCEPTED',
    NEW_MESSAGE: 'NEW-MESSAGE'
};
module.exports = CHAT_EVENTS;